name: gauge_reader_org_clone
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - ld_impl_linux-aarch64=2.44
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.2
  - pip=24.3.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.8.20
  - python_abi=3.8
  - reactivex=4.0.4
  - readline=8.2
  - tk=8.6.13
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==45.0.6
      - cycler==0.12.1
      - cython==3.1.3
      - filelock==3.14.0
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - idna==3.10
      - imageio==2.35.1
      - imgaug==0.4.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - influxdb==5.3.2
      - influxdb-client==1.49.0
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lmdb==1.7.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==2.0.0
      - mmdet==3.0.0
      - mmengine==0.7.2
      - mmocr==1.0.0
      - model-index==0.1.11
      - mpmath==1.3.0
      - msgpack==1.1.1
      - networkx==3.1
      - ninja==1.13.0
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - project-3301==0.1.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyclipper==1.3.0.post6
      - pycocotools==2.0.7
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - rapidfuzz==3.9.7
      - requests==2.28.2
      - rich==13.4.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tomli==2.2.1
      - torch==2.0.0
      - torchaudio==2.0.0
      - torchvision==0.15.0
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - ultralytics==8.3.184
      - ultralytics-thop==2.0.16
      - urllib3==1.26.20
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /home/is307/miniforge3/envs/gauge_reader_org_clone
